Repository securesign/scaffolding, pull requests merged in 2023-11, with the labels that each got.

#113 pipelines: add source image builds to all pipelines
  .tekton/cloudsqlproxy-pull-request.yaml
  .tekton/cloudsqlproxy-push.yaml
  .tekton/createcerts-pull-request.yaml
  .tekton/createcerts-push.yaml
  .tekton/createctconfig-pull-request.yaml
  .tekton/createctconfig-push.yaml
  .tekton/createdb-pull-request.yaml
  .tekton/createdb-push.yaml
  .tekton/createtree-pull-request.yaml
  .tekton/createtree-push.yaml
  .tekton/ct-server-pull-request.yaml
  .tekton/ct-server-push.yaml
  .tekton/ctlog-managectroots-pull-request.yaml
  .tekton/ctlog-managectroots-push.yaml
  .tekton/ctlog-verifyfulcio-pull-request.yaml
  .tekton/ctlog-verifyfulcio-push.yaml
  .tekton/tuf-server-pull-request.yaml
  .tekton/tuf-server-push.yaml
Labels: approved, lgtm

#116 :robot: triggering CI on branch 'redhat-v0.6.5' after synching from upstream/v0.6.5
  Dockerfile.cloudsqlproxy
  Dockerfile.createcerts
  Dockerfile.createctconfig
  Dockerfile.createdb
  Dockerfile.createtree
  Dockerfile.ct-server
  Dockerfile.ctlog-managectroots
  Dockerfile.ctlog-verifyfulcio
  Dockerfile.tuf-server
  ci
Labels: kind/sync-fork-to-upstream, approved

#128 chore add all additional Dockerfiles for scaffolding
  Dockerfile.cloudsqlproxy
  Dockerfile.createcerts
  Dockerfile.createctconfig
  Dockerfile.createdb
  Dockerfile.createtree
  Dockerfile.ct-server
  Dockerfile.ctlog-managectroots
  Dockerfile.ctlog-verifyfulcio
  Dockerfile.tuf-server
  hack/build-assets/certificate-transparency-go-1.1.6.tar.gz
  hack/build-assets/go.mod
  hack/build-assets/go.sum
Labels: lgtm, ok-to-test

#132 [SECURESIGN-210] chore: update base images for some components
  Dockerfile.cloudsqlproxy
  Dockerfile.createdb
  Dockerfile.createtree
Labels: lgtm

#142 [SECURESIGN-272] Enable Source Container Builds
  .tekton/creatctconfig-0-6-pull-request.yaml
  .tekton/creatctconfig-0-6-push.yaml
  .tekton/ct-server-0-6-pull-request.yaml
  .tekton/ct-server-0-6-push.yaml
  .tekton/ctlog-managectroots-0-6-pull-request.yaml
  .tekton/ctlog-managectroots-0-6-push.yaml
  .tekton/ctlog-verify-fulcio-0-6-pull-request.yaml
  .tekton/ctlog-verify-fulcio-0-6-push.yaml
  .tekton/tuf-server-0-6-pull-request.yaml
  .tekton/tuf-server-0-6-push.yaml
Labels: lgtm

#125 adding dockerfile for securesign-redis
  Dockerfile.redis
Labels: lgtm

#148 optimizing build conditions to reduce RHTAP workloads
  .tekton/cloudsqlproxy-0-6-pull-request.yaml
  .tekton/cloudsqlproxy-0-6-push.yaml
  .tekton/createcerts-1-0-gamma-pull-request.yaml
  .tekton/createcerts-1-0-gamma-push.yaml
  .tekton/createdb-0-6-pull-request.yaml
  .tekton/createdb-0-6-push.yaml
  .tekton/createtree-0-6-pull-request.yaml
  .tekton/createtree-0-6-push.yaml
  .tekton/ct-server-0-6-pull-request.yaml
  .tekton/ct-server-0-6-push.yaml
  .tekton/ctlog-managectroots-0-6-pull-request.yaml
  .tekton/ctlog-managectroots-0-6-push.yaml
  .tekton/ctlog-verify-fulcio-0-6-pull-request.yaml
  .tekton/ctlog-verify-fulcio-0-6-push.yaml
  .tekton/tuf-server-0-6-pull-request.yaml
  .tekton/tuf-server-0-6-push.yaml
Labels: lgtm
