Repository securesign/scaffolding, pull requests merged in 2023-10, with the labels that each got.

#70 :robot: triggering CI on branch 'redhat-v0.6.5' after synching from upstream/v0.6.5
  ci
  redhat/release/update-to-head.sh
Labels: kind/sync-fork-to-upstream

#72 :robot: triggering CI on branch 'redhat-v0.6.5' after synching from upstream/v0.6.5
  ci
Labels: kind/sync-fork-to-upstream

#74 :robot: triggering CI on branch 'redhat-v0.6.5' after synching from upstream/v0.6.5
  Dockerfile.cloudsqlproxy
  Dockerfile.createcerts
  Dockerfile.createctconfig
  Dockerfile.createdb
  Dockerfile.createtree
  Dockerfile.ct-server
  Dockerfile.ctlog-managectroots
  Dockerfile.ctlog-verifyfulcio
  Dockerfile.tuf-server
  ci
  hack/build-assets/certificate-transparency-go-1.1.6.tar.gz
  hack/build-assets/go.mod
  hack/build-assets/go.sum
  redhat/release/update-to-head.sh
Labels: kind/sync-fork-to-upstream, approved

#80 SECURESIGN-115 | Add new label to dockerfiles for Comet
  redhat/overlays/Dockerfile.cloudsqlproxy
  redhat/overlays/Dockerfile.createcerts
  redhat/overlays/Dockerfile.createctconfig
  redhat/overlays/Dockerfile.createdb
  redhat/overlays/Dockerfile.createtree
  redhat/overlays/Dockerfile.ct-server
  redhat/overlays/Dockerfile.ctlog-managectroots
  redhat/overlays/Dockerfile.ctlog-verifyfulcio
  redhat/overlays/Dockerfile.tuf-server
Labels: approved, lgtm

#82 chore: modify update script to avoid merge conflicts
  redhat/release/update-to-head.sh
Labels: approved, lgtm

#84 fix ct-server image and update shas
  redhat/overlays/Dockerfile.cloudsqlproxy
  redhat/overlays/Dockerfile.createcerts
  redhat/overlays/Dockerfile.createctconfig
  redhat/overlays/Dockerfile.createdb
  redhat/overlays/Dockerfile.createtree
  redhat/overlays/Dockerfile.ct-server
  redhat/overlays/Dockerfile.ctlog-managectroots
  redhat/overlays/Dockerfile.ctlog-verifyfulcio
  redhat/overlays/Dockerfile.tuf-server
Labels: approved, lgtm

#88 Remove patch file
  redhat/overlays/.github/workflows/verify.yml
  redhat/patches/0001-shellcheck.patch
  redhat/release/update-to-head.sh
Labels: approved, lgtm

#90 Redhat v0.6.5 ci
  .tekton/cloudsqlproxy-pull-request.yaml
  .tekton/cloudsqlproxy-push.yaml
  .tekton/createcerts-pull-request.yaml
  .tekton/createcerts-push.yaml
  .tekton/createctconfig-pull-request.yaml
  .tekton/createctconfig-push.yaml
  .tekton/createdb-pull-request.yaml
  .tekton/createdb-push.yaml
  .tekton/createtree-pull-request.yaml
  .tekton/createtree-push.yaml
  .tekton/ct-server-pull-request.yaml
  .tekton/ct-server-push.yaml
  .tekton/ctlog-managectroots-pull-request.yaml
  .tekton/ctlog-managectroots-push.yaml
  .tekton/ctlog-verifyfulcio-pull-request.yaml
  .tekton/ctlog-verifyfulcio-push.yaml
  .tekton/tuf-server-pull-request.yaml
  .tekton/tuf-server-push.yaml
  Dockerfile.cloudsqlproxy
  Dockerfile.createcerts
  Dockerfile.createctconfig
  Dockerfile.createdb
  Dockerfile.createtree
  Dockerfile.ct-server
  Dockerfile.ctlog-managectroots
  Dockerfile.ctlog-verifyfulcio
  Dockerfile.tuf-server
  ci
  hack/build-assets/certificate-transparency-go-1.1.6/certificate-transparency-go-1.1.6.tar.gz
  hack/build-assets/certificate-transparency-go-1.1.6/go.mod
  hack/build-assets/certificate-transparency-go-1.1.6/go.sum
  redhat/overlays/.github/workflows/verify.yml
  redhat/release/update-to-head.sh
Labels: approved

#92 :robot: triggering CI on branch 'redhat-v0.6.5' after synching from upstream/v0.6.5
  Dockerfile.cloudsqlproxy
  Dockerfile.createcerts
  Dockerfile.createctconfig
  Dockerfile.createdb
  Dockerfile.createtree
  Dockerfile.ct-server
  Dockerfile.ctlog-managectroots
  Dockerfile.ctlog-verifyfulcio
  Dockerfile.tuf-server
  ci
  hack/build-assets/certificate-transparency-go-1.1.6/certificate-transparency-go-1.1.6.tar.gz
  hack/build-assets/certificate-transparency-go-1.1.6/go.mod
  hack/build-assets/certificate-transparency-go-1.1.6/go.sum
  redhat/overlays/.github/workflows/verify.yml
  redhat/release/update-to-head.sh
Labels: kind/sync-fork-to-upstream, approved

#97 update path in test, update shas for test
  .tekton/cloudsqlproxy-pull-request.yaml
  .tekton/cloudsqlproxy-push.yaml
  .tekton/createcerts-pull-request.yaml
  .tekton/createcerts-push.yaml
  .tekton/createctconfig-pull-request.yaml
  .tekton/createctconfig-push.yaml
  .tekton/createdb-pull-request.yaml
  .tekton/createdb-push.yaml
  .tekton/createtree-pull-request.yaml
  .tekton/createtree-push.yaml
  .tekton/ct-server-pull-request.yaml
  .tekton/ct-server-push.yaml
  .tekton/ctlog-managectroots-pull-request.yaml
  .tekton/ctlog-managectroots-push.yaml
  .tekton/ctlog-verifyfulcio-pull-request.yaml
  .tekton/ctlog-verifyfulcio-push.yaml
  .tekton/scaffolding-unit-test.yaml
  .tekton/tuf-server-pull-request.yaml
  .tekton/tuf-server-push.yaml
Labels: approved

#99 update path in test, update shas for test
  .tekton/cloudsqlproxy-pull-request.yaml
  .tekton/cloudsqlproxy-push.yaml
  .tekton/createcerts-pull-request.yaml
  .tekton/createcerts-push.yaml
  .tekton/createctconfig-pull-request.yaml
  .tekton/createctconfig-push.yaml
  .tekton/createdb-pull-request.yaml
  .tekton/createdb-push.yaml
  .tekton/createtree-pull-request.yaml
  .tekton/createtree-push.yaml
  .tekton/ct-server-pull-request.yaml
  .tekton/ct-server-push.yaml
  .tekton/ctlog-managectroots-pull-request.yaml
  .tekton/ctlog-managectroots-push.yaml
  .tekton/ctlog-verifyfulcio-pull-request.yaml
  .tekton/ctlog-verifyfulcio-push.yaml
  .tekton/scaffolding-unit-test.yaml
  .tekton/tuf-server-pull-request.yaml
  .tekton/tuf-server-push.yaml
Labels: approved

#95 :robot: triggering CI on branch 'redhat-v0.6.5' after synching from upstream/v0.6.5
  ci
  redhat/build-assets/certificate-transparency-go-1.1.6/certificate-transparency-go-1.1.6.tar.gz
  redhat/build-assets/certificate-transparency-go-1.1.6/go.mod
  redhat/build-assets/certificate-transparency-go-1.1.6/go.sum
  redhat/release/update-to-head.sh
Labels: kind/sync-fork-to-upstream, approved

#100 chore: update to latest Red Hat UBI images
  redhat/overlays/Dockerfile.cloudsqlproxy
  redhat/overlays/Dockerfile.createcerts
  redhat/overlays/Dockerfile.createctconfig
  redhat/overlays/Dockerfile.createdb
  redhat/overlays/Dockerfile.createtree
  redhat/overlays/Dockerfile.ct-server
  redhat/overlays/Dockerfile.ctlog-managectroots
  redhat/overlays/Dockerfile.ctlog-verifyfulcio
  redhat/overlays/Dockerfile.tuf-server
Labels: approved, lgtm

#102 :robot: triggering CI on branch 'redhat-v0.6.5' after synching from upstream/v0.6.5
  Dockerfile.cloudsqlproxy
  Dockerfile.createcerts
  Dockerfile.createctconfig
  Dockerfile.createdb
  Dockerfile.createtree
  Dockerfile.ct-server
  Dockerfile.ctlog-managectroots
  Dockerfile.ctlog-verifyfulcio
  Dockerfile.tuf-server
  ci
Labels: kind/sync-fork-to-upstream, approved

#103 deps(ubi-minimal): bump to latest sha256
  redhat/overlays/Dockerfile.cloudsqlproxy
  redhat/overlays/Dockerfile.createcerts
  redhat/overlays/Dockerfile.createctconfig
  redhat/overlays/Dockerfile.createdb
  redhat/overlays/Dockerfile.createtree
  redhat/overlays/Dockerfile.ct-server
  redhat/overlays/Dockerfile.ctlog-managectroots
  redhat/overlays/Dockerfile.ctlog-verifyfulcio
  redhat/overlays/Dockerfile.tuf-server
Labels: approved, lgtm

#104 :robot: triggering CI on branch 'redhat-v0.6.5' after synching from upstream/v0.6.5
  Dockerfile.cloudsqlproxy
  Dockerfile.createcerts
  Dockerfile.createctconfig
  Dockerfile.createdb
  Dockerfile.createtree
  Dockerfile.ct-server
  Dockerfile.ctlog-managectroots
  Dockerfile.ctlog-verifyfulcio
  Dockerfile.tuf-server
  ci
Labels: kind/sync-fork-to-upstream, approved

#106 feat: Add GH action
  .github/workflows/cronjobs.yaml
Labels: approved, lgtm

#110 chore: remove unit tests from RHTAP pipeline
  .tekton/cloudsqlproxy-pull-request.yaml
  .tekton/cloudsqlproxy-push.yaml
  .tekton/createcerts-pull-request.yaml
  .tekton/createcerts-push.yaml
  .tekton/createctconfig-pull-request.yaml
  .tekton/createctconfig-push.yaml
  .tekton/createdb-pull-request.yaml
  .tekton/createdb-push.yaml
  .tekton/createtree-pull-request.yaml
  .tekton/createtree-push.yaml
  .tekton/ct-server-pull-request.yaml
  .tekton/ct-server-push.yaml
  .tekton/ctlog-managectroots-pull-request.yaml
  .tekton/ctlog-managectroots-push.yaml
  .tekton/ctlog-verifyfulcio-pull-request.yaml
  .tekton/ctlog-verifyfulcio-push.yaml
  .tekton/tuf-server-pull-request.yaml
  .tekton/tuf-server-push.yaml
Labels: approved, lgtm
